function L = getAdjointStiffness( obj, U )

  L = gf_asm('volumic',[ ...
             'u=data(#2);',...
             't=comp(vGrad(#2).vGrad(#2).Base(#1));',...
             'e=(t{:,2,3,:,5,6,:}+t{:,3,2,:,5,6,:}',...
             '+t{:,2,3,:,6,5,:}+t{:,3,2,:,6,5,:})/2;',...
             'g=e(:,i,j,:,i,j,:);M(#2,#1)+=g(j,:,:).u(j)'],...
             obj.integrationMethod,...
             obj.meshFemD,...
             obj.meshFemU,...
             U);
end
