function Khat = getKhat( obj, muDsc )
    Khat = gf_asm( 'linear elasticity',...
                  obj.integrationMethod,...
                  obj.meshFemU, obj.meshFemD,...
                  obj.muZeros,...
                  muDsc);
end
